# Generated by Django 5.1.1 on 2024-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="weather_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("city", models.CharField(max_length=50)),
                ("temperature", models.IntegerField(max_length=2)),
                ("phValue", models.IntegerField(max_length=1)),
                ("windSpeed", models.CharField(max_length=3)),
                ("rainfall", models.CharField(max_length=5)),
            ],
        ),
    ]
