# Generated by Django 5.1.1 on 2024-10-05 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherreport", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weather_report",
            name="phValue",
        ),
        migrations.RemoveField(
            model_name="weather_report",
            name="windSpeed",
        ),
        migrations.AddField(
            model_name="weather_report",
            name="ph_value",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weather_report",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weather_report",
            name="wind_speed",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weather_report",
            name="rainfall",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="weather_report",
            name="temperature",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(-50),
                    django.core.validators.MaxValueValidator(50),
                ]
            ),
        ),
    ]
