# Generated by Django 5.1.1 on 2024-10-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="predictions_yield",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("soil_quality", models.CharField(max_length=20)),
                ("environment_factors", models.CharField(max_length=20)),
                ("irrigation", models.CharField(max_length=20)),
                ("prediction", models.FloatField()),
            ],
        ),
    ]
